package com.example.nhviewer.ui.theme

import androidx.compose.ui.graphics.Color

// 种子色（玫红）
val SeedRose = Color(0xFFE91E8C)

// ── 静态亮色模式色板 ──
val LightPrimary = Color(0xFFB90063)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFD9E2)
val LightOnPrimaryContainer = Color(0xFF3E001D)
val LightSecondary = Color(0xFF74565F)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFFD9E2)
val LightOnSecondaryContainer = Color(0xFF2B151C)
val LightTertiary = Color(0xFF7C5635)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFDCC1)
val LightOnTertiaryContainer = Color(0xFF2E1500)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFFBFF)
val LightOnBackground = Color(0xFF201A1B)
val LightSurface = Color(0xFFFFFBFF)
val LightOnSurface = Color(0xFF201A1B)
val LightSurfaceVariant = Color(0xFFF2DDE1)
val LightOnSurfaceVariant = Color(0xFF514346)
val LightOutline = Color(0xFF837376)
val LightOutlineVariant = Color(0xFFD5C2C5)
val LightScrim = Color(0xFF000000)
val LightInverseSurface = Color(0xFF352F30)
val LightInverseOnSurface = Color(0xFFFAEEF0)
val LightInversePrimary = Color(0xFFFFB1C8)

// 亮色模式下的 MD3 容器色彩分层
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF8F2F3)
val LightSurfaceContainer = Color(0xFFF2ECEE)
val LightSurfaceContainerHigh = Color(0xFFECE6E8)
val LightSurfaceContainerHighest = Color(0xFFE6E0E2)

// ── 静态暗色模式色板 ──
val DarkPrimary = Color(0xFFFFB1C8)
val DarkOnPrimary = Color(0xFF650033)
val DarkPrimaryContainer = Color(0xFF8E004A)
val DarkOnPrimaryContainer = Color(0xFFFFD9E2)
val DarkSecondary = Color(0xFFFFB1C8)
val DarkOnSecondary = Color(0xFF422931)
val DarkSecondaryContainer = Color(0xFF5B3F47)
val DarkOnSecondaryContainer = Color(0xFFFFD9E2)
val DarkTertiary = Color(0xFFEFBD94)
val DarkOnTertiary = Color(0xFF48290C)
val DarkTertiaryContainer = Color(0xFF623F20)
val DarkOnTertiaryContainer = Color(0xFFFFDCC1)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF201A1B)
val DarkOnBackground = Color(0xFFECE0E2)
val DarkSurface = Color(0xFF201A1B)
val DarkOnSurface = Color(0xFFECE0E2)
val DarkSurfaceVariant = Color(0xFF514346)
val DarkOnSurfaceVariant = Color(0xFFD5C2C5)
val DarkOutline = Color(0xFF9E8C90)
val DarkOutlineVariant = Color(0xFF514346)
val DarkScrim = Color(0xFF000000)
val DarkInverseSurface = Color(0xFFECE0E2)
val DarkInverseOnSurface = Color(0xFF201A1B)
val DarkInversePrimary = Color(0xFFB90063)

// 暗色模式下的 MD3 容器色彩分层
val DarkSurfaceContainerLowest = Color(0xFF0F0B0C)
val DarkSurfaceContainerLow = Color(0xFF1D1617)
val DarkSurfaceContainer = Color(0xFF211A1B)
val DarkSurfaceContainerHigh = Color(0xFF2C2426)
val DarkSurfaceContainerHighest = Color(0xFF372F30)